//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyMSL_W.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class learn
    {
        public string image_id { get; set; }
        public string image_type { get; set; }
        public string image_name { get; set; }
        public string image_name_malay { get; set; }
        public string image_dir { get; set; }
        public string image_desc { get; set; }
        public string image_desc_malay { get; set; }
    }
}
