//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyMSL_W.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class progress
    {
        public int p_id { get; set; }
        public string user_id { get; set; }
        public string content_id { get; set; }
        public string content_name { get; set; }
        public string content_desc { get; set; }
        public System.DateTime date_completed { get; set; }
    }
}
