//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyMSL_W.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public string question_id { get; set; }
        public string question_type { get; set; }
        public string image_dir { get; set; }
        public string question1 { get; set; }
        public string answer { get; set; }
        public int answerindex { get; set; }
        public string answer1 { get; set; }
        public string answer2 { get; set; }
        public string answer3 { get; set; }
        public string answer4 { get; set; }
    }
}
