//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyMSL_W.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spellingquestion
    {
        public string question_id { get; set; }
        public string question_type { get; set; }
        public string image_dir { get; set; }
        public string answer { get; set; }
        public string image1_dir { get; set; }
        public string image2_dir { get; set; }
        public string image3_dir { get; set; }
        public string image4_dir { get; set; }
        public string image5_dir { get; set; }
        public string image6_dir { get; set; }
        public string image7_dir { get; set; }
        public string image8_dir { get; set; }
    }
}
